#!/usr/bin/env python3
"""Rebuild the ASM research ledger safely from the preserved 35-row prefix."""
import csv
import re
from pathlib import Path
from urllib.parse import urlsplit, urlunsplit, parse_qsl, urlencode

ROOT = Path('/home/user/ASM-research')
WORKING = ROOT / 'SOURCES_WORKING.csv'
BACKUP = ROOT / 'SOURCES_PARTIAL_RECOVERY_BACKUP.csv'
TEMP = ROOT / 'SOURCES_WORKING.rebuilt.tmp.csv'
FIELDS = ['id','source_type','subject','title_or_locator','claim_or_coverage','status','reviewed_on','canonical_url','notes']
DATE = '2026-10-05'

# Preserve the currently available prefix only after confirming that both copies
# contain the same valid S001-S035 rows.
def read_prefix(path):
    with path.open('r', encoding='utf-8-sig', newline='') as f:
        reader = csv.DictReader(f)
        if reader.fieldnames != FIELDS:
            raise SystemExit(f'Unexpected CSV header in {path}: {reader.fieldnames!r}')
        rows = list(reader)
    if len(rows) != 35 or [r['id'] for r in rows] != [f'S{i:03d}' for i in range(1,36)]:
        raise SystemExit(f'{path} is not the expected intact 35-row prefix')
    if any(not all(r.get(k) for k in FIELDS if k != 'notes') for r in rows):
        raise SystemExit(f'Empty required field in preserved prefix: {path}')
    return rows

prefix = read_prefix(WORKING)
backup = read_prefix(BACKUP)
if prefix != backup:
    raise SystemExit('Working CSV and partial backup differ; refusing to choose one silently')

extra = []
def add(kind, subject, title, claim, status, url, notes):
    extra.append({
        'source_type': kind,
        'subject': subject,
        'title_or_locator': title,
        'claim_or_coverage': claim,
        'status': status,
        'reviewed_on': DATE,
        'canonical_url': url,
        'notes': notes,
    })

# Re-indexed external sources S036-S087. The earlier ledger was truncated;
# re-indexed entries are explicitly marked as recovered/rechecked.
recovered = 'Recovered/re-indexed after CSV truncation; source-claim confidence follows the status field and was reassessed 2026-10-05.'
add('forum','Greenbone','QoD and missing findings thread','Community explanation of why lower-QoD results may be hidden by default and why lowering the threshold can increase false positives.','secondary forum reviewed', 'https://forum.greenbone.net/t/vulnerabilities-not-being-detected/9963', recovered+' Single troubleshooting discussion, not a performance benchmark.')
add('forum','Greenbone','2025 empty/fast scan troubleshooting','One Community Edition user reported a five-second scan with an empty report; replies point to alive-check/setup diagnostics.','secondary forum reviewed','https://forum.greenbone.net/t/scan-finishes-in-5-seconds-with-no-results-docker-community-edition/21199',recovered+' Individual case; not evidence of general product failure.')
add('official-docs','Purple Knight','FAQ','Free point-in-time AD/Entra assessment; vendor says no AD changes and no elevated on-prem AD permission, but scans can use LDAP/RPC. Entra setup requires a separate app registration and Graph consent.','primary docs reviewed','https://www.semperis.com/purple-knight/faq/',recovered+' Vendor statements; verify behavior in the downloaded binary only if selected.')
add('official-product','Purple Knight','Product page / current edition','Purple Knight 5.1 Community; AD, Entra and Okta indicators and risk report.','primary product page reviewed','https://www.semperis.com/purple-knight/',recovered+' Closed binary; feature counts differ across page sections, so no exact count adopted.')
add('official-docs','Purple Knight','Security indicators list','Canonical Semperis catalog covers AD, Entra, GPO, hybrid, Kerberos and Okta indicators; useful to map coverage against SharpHound and Maester.','primary indicator catalog reviewed','https://www.semperis.com/purple-knight/security-indicators/',recovered+' Vendor coverage claims; not source-code evidence.')
add('official-code','Purple Knight','PK-AADAppReg helper repository','PowerShell helper can create/update/delete Entra apps, grant Graph permissions/consent, create/delete client secrets; its DSP mode also grants write scopes and Directory Writers membership.','primary repo reviewed; code audit deferred','https://github.com/Semperis/PK-AADAppReg',recovered+' Provisioning is state-changing; never run automatically as part of an assessment; use only a reviewed PK-only mode if operator explicitly chooses it.')
add('official-docs','Forest Druid','FAQ','Free Tier-0 attack-path tool; vendor says it needs AD read permission, collects all forest domains available to the logged-on user, and has no phone-home.','primary docs reviewed','https://www.semperis.com/forest-druid/faq/',recovered+' Vendor statements; exact scope behavior needs code/binary review.')
add('official-blog','Forest Druid','Data collection and offline analysis','Describes LDAP collection, local Backend/Database storage and copying a snapshot for offline analysis.','primary blog reviewed','https://www.semperis.com/blog/strengthening-incident-response-with-forest-druid/',recovered+' Vendor walkthrough; not independent privacy verification.')
add('official-product','Forest Druid','Product page','Tier-0-focused attack-path analysis for AD and Entra; vendor page currently advertises a free community tool.','primary product page reviewed','https://www.semperis.com/forest-druid/',recovered+' Version differs from the docs portal; verify installer version if selected.')
add('vendor-video','Forest Druid','Embedded demo video locator','Vendor transcript demonstrates inside-out Tier-0 perimeter analysis and prioritization of one-hop relationships.','vendor video transcript reviewed','https://fast.wistia.net/embed/channel/870zs3b7eo?wchannelid=870zs3b7eo&wmediaid=vvkc5g3wpq',recovered+' Demonstration of the vendor product; not independent evidence of privacy or completeness.')
add('official-code','GPOZaurr','Repository','PowerShell diagnostics/reporting plus repair/remediation functions for GPO/SYSVOL.','primary repo reviewed; code audit deferred','https://github.com/EvotecIT/GPOZaurr',recovered+' The repository has no separate permissive license notice; PowerShell Gallery metadata says “All rights reserved.” Do not infer commercial rights.')
add('official-release','GPOZaurr','v1.1.11 release','Release page dates v1.1.11 to 2026-09-20.','primary release reviewed','https://github.com/EvotecIT/GPOZaurr/releases/tag/v1.1.11',recovered+' Release activity is not a substitute for license or code review.')
add('official-package','GPOZaurr','PowerShell Gallery package 1.1.11','Gallery metadata requires PowerShell 5.1 and lists mutating Add/Remove functions, Get-GPOZaurrPassword, and repair functions.','primary package page reviewed','https://www.powershellgallery.com/packages/GPOZaurr/1.1.11',recovered+' Gallery metadata states “All rights reserved”; do not infer commercial permission.')
add('official-blog','GPOZaurr','Maintainer article on reports and fixes','Describes one-command GPO reports and automated/manual remediation workflows.','primary maintainer blog reviewed','https://evotec.xyz/the-only-command-you-will-ever-need-to-understand-and-fix-your-group-policies-gpo/',recovered+' Useful feature map; maintainer-authored and older than current release.')
add('official-code','Testimo','Repository','PowerShell AD health-check test suite; dependency and execution surface to compare with Maester.','primary repo reviewed; code audit deferred','https://github.com/EvotecIT/Testimo',recovered+' No explicit license identified in the reviewed repository; do not assume permission for paid work.')
add('official-release','Testimo','v0.0.92 release','Latest release metadata shows v0.0.92 published 2026-09-20.','primary release reviewed','https://github.com/EvotecIT/Testimo/releases',recovered+' Currentness confirmed; 0.0.x version line.')
add('official-package','Testimo','PowerShell Gallery package 0.0.92','Gallery metadata shows PowerShell 5.1 minimum, dependencies including GPOZaurr/ADEssentials/PSWriteHTML, and all-rights-reserved copyright.','primary package page reviewed','https://www.powershellgallery.com/packages/Testimo/0.0.92',recovered+' Package publication does not grant a commercial-use license; dependency chain requires review.')
add('official-code','PingCastle','Repository','Current PingCastle source repository and product documentation.','primary repo reviewed; code audit deferred','https://github.com/netwrix/pingcastle',recovered+' Community license is separately reviewed; paid external assessment is excluded without commercial grant.')
add('official-license','PingCastle','README license terms','Non-Profit OSL 3.0 permits internal corporate use but bars monetized third-party service without a commercial license.','primary license terms reviewed','https://github.com/netwrix/pingcastle/blob/master/README.md',recovered+' Legal interpretation should be confirmed by counsel for a specific contract.')
add('official-release','PingCastle','Current releases','Latest release shown as 4.0.0.20 (2026-08-11), with AD/Entra reporting and rule fixes.','primary release reviewed','https://github.com/netwrix/pingcastle/releases',recovered+' Release notes are not a substitute for paid-service licensing.')
add('official-code','Locksmith','Upstream repository','Active PowerShell AD CS audit/remediation module; upstream main updated 2026-10-03 and includes ESC17 detection.','primary upstream repo reviewed; code audit deferred','https://github.com/jakehildreth/Locksmith',recovered+' Main branch is ahead of latest tagged release; distinguish source from published Gallery package and separate audit from remediation functions.')
add('official-license','Locksmith','Upstream LICENSE','MIT plus Commons Clause v1.0; Commons Clause prohibits fee-based products/services whose value derives substantially from the software, including consulting/support.','primary upstream license reviewed','https://github.com/jakehildreth/Locksmith/blob/main/LICENSE',recovered+' Likely incompatible with a fee-based assessment substantially reliant on this tool; obtain legal confirmation/permission before paid use.')
add('official-release','Locksmith','Release history','Latest tagged GitHub release is v2025.9.8 (2025-09-11), signed/verified; current main has newer changes.','primary upstream releases/tags reviewed','https://github.com/jakehildreth/Locksmith/releases',recovered+' Do not treat the older tag as equivalent to the newer PowerShell Gallery package or main branch.')
add('official-code','ADRecon','Repository','PowerShell AD inventory/report; last repository commit shown as 2024-10-15. README says default collection excludes ACLs/Kerberoast but may collect LAPS passwords and BitLocker recovery keys with privileged access.','primary repo and README reviewed; code audit deferred','https://github.com/adrecon/ADRecon',recovered+' Scope/secret collection depends on selected options and permissions; code is not a candidate for automation under current secret-handling constraints.')
add('official-package','Locksmith','PowerShell Gallery package 2026.1.4.1426','Gallery package targets PowerShell 5.1 and has no module dependencies; its file list includes a dated ADCSIssues.CSV whose contents were not inspected.','primary package page reviewed','https://www.powershellgallery.com/packages/Locksmith/2026.1.4.1426',recovered+' Gallery metadata says all rights reserved; compare package contents with GitHub source and Commons Clause before use.')
add('official-license','ADRecon','LICENSE.md','Repository identifies AGPL-3.0.','primary license reviewed','https://github.com/adrecon/ADRecon/blob/master/LICENSE.md',recovered+' AGPL-3.0 permits commercial use subject to copyleft and notice obligations; verify consequences before modification/integration.')
add('official-code','AzureADRecon','Repository','PowerShell Entra inventory/report tool; README lists tenant/users/groups/devices/service principals/roles/Conditional Access and shows a code fix on 2026-08-24.','primary repo and README reviewed; code audit deferred','https://github.com/adrecon/AzureADRecon',recovered+' README conflicts between AzureAD module prerequisite and Microsoft Graph method/scopes; verify current Graph API code. Requires broad delegated scopes and writes detailed local reports.')
add('official-license','AzureADRecon','LICENSE','Repository declares AGPL-3.0.','primary license reviewed','https://github.com/adrecon/AzureADRecon/blob/master/LICENSE',recovered+' AGPL-3.0; inspect actual Graph permissions and API version before any use.')
add('official-code','PentAGI','Repository','MIT-licensed autonomous multi-agent pentest system with agents/tools; issue tracker documents an opt-in safety classifier.','primary repo reviewed; code audit deferred','https://github.com/vxcontrol/pentagi',recovered+' Autonomous execution is not eligible for direct target access under ASM gates; MIT notice obligations still apply.')
add('reddit','Active Directory tools','r/activedirectory PingCastle-like thread','Community compares PingCastle, Purple Knight, Forest Druid, AD ACL tools and GPO tools.','secondary Reddit reviewed','https://www.reddit.com/r/activedirectory/comments/1iz1uvp/ping_castle_like/',recovered+' Recommendations/opinions, not measured coverage or license proof.')
add('reddit','Active Directory tools','r/activedirectory resiliency checks','Community contrasts health checks with BloodHound attack-path graphing and notes setup/coverage overlap.','secondary Reddit reviewed','https://www.reddit.com/r/activedirectory/comments/1ignfq9/ad_resiliency_checks/',recovered+' Anecdotal and environment-specific.')
add('official-issue','PentAGI','Issue #337 Docker socket escape concern','Reporter described a sandbox-to-host Docker socket escape path; maintainer later closed issue stating default DinD is off and a separate daemon should be used when needed.','primary issue and maintainer response reviewed; current code not independently checked','https://github.com/vxcontrol/pentagi/issues/337',recovered+' Configuration-dependent mitigation is self-reported; verify shipped compose/config before relying on it.')
add('official-pull-request','PentAGI','PR #356 sandbox/proxy hardening discussion','Patch and review discussion around container/command isolation; inspect merged code and exact deployment profile before relying on it.','primary PR and maintainer response reviewed; not treated as verified fix','https://github.com/vxcontrol/pentagi/pull/356',recovered+' Maintainer rejected the PR on 2026-09-23: path/method filtering could still allow privileged containers, and the sandbox remained on the DB network.')
add('official-issue','PentAGI','Issue #407 Deaf Guard behavior','Issue documents Deaf Guard defaulting to enabled/log: a BLOCK-tier command still executes; warn blocks BLOCK-tier, enforce blocks BLOCK and WARN; runtime changes apply next flow.','primary issue reviewed','https://github.com/vxcontrol/pentagi/issues/407',recovered+' Exact current config/code must be pinned; do not treat default logging as a gate.')
add('official-code','Strix','Repository','Apache-2.0 autonomous web security agent with terminal/browser/Python tools and real exploit validation; latest v1.7.0 released 2026-10-05.','primary repo/license/release reviewed; code audit deferred','https://github.com/usestrix/strix',recovered+' Architecture only; no direct ASM target access. Local deployment does not guarantee air-gap or privacy.')
add('official-issue','Strix','Issue #1268 local vs air-gapped behavior','Open discussion distinguishes local runtime from fully local/air-gapped scans; remote LLM, telemetry and image pulls may still send data or require network.','primary issue reviewed; current code check deferred','https://github.com/usestrix/strix/issues/1268',recovered+' Issue is not proof of current release behavior; validate pinned version and traffic paths.')
add('official-release','Strix','v1.7.0 release','Release dated 2026-10-05; includes changes to Exa search query scope, request logging and runtime controls, but does not by itself settle full local privacy.','primary release reviewed','https://github.com/usestrix/strix/releases/tag/v1.7.0',recovered+' Very recent release; issue #1268 remains a separate privacy checkpoint.')
add('official-code','Shannon','Official Keygraph repository','Current Shannon 3.0 combines source-informed analysis with real exploitation; repository documents local model endpoints and local result storage.','primary repo reviewed; code audit deferred','https://github.com/KeygraphHQ/shannon',recovered+' AGPL-3.0; real exploitation makes this architecture-only for ASM.')
add('official-license','Shannon','LICENSE','GNU Affero GPL v3.0.','primary license reviewed','https://github.com/KeygraphHQ/shannon/blob/main/LICENSE',recovered+' Review obligations if modified/distributed or exposed as a network service.')
add('official-code','AIDA','Repository','AGPL-3.0 autonomous pentesting platform with browser/MCP/tool orchestration; repository’s v1.0.0-alpha commit is dated 2026-01-31.','primary repo/license reviewed; code audit deferred','https://github.com/Vasco0x4/AIDA',recovered+' Can execute commands/HTTP; architecture-only, not an ASM plug-in. AGPL obligations apply to covered modifications/distribution/network service.')
add('official-docs','AIDA','README and CLI modes','Documents host/local execution mode and command execution options; defaults and bypass flags require code review.','primary README reviewed; code audit deferred','https://github.com/Vasco0x4/AIDA/blob/main/README.md',recovered+' Do not use --yes or host execution; exact current tag must be pinned.')
add('official-code','Dark Moon','Repository','Autonomous AI pentest project advertising web/API/cloud/AD agents and a privacy gateway; main updated 2026-10-01. README/release badge says GPLv3, but no conventional root LICENSE file was found.','primary repo/license-path checks reviewed; code audit deferred','https://github.com/ASCIT31/Dark-Moon',recovered+' Treat GPLv3 grant as unverified until the exact tag’s license text is located; issue #40 records an earlier privacy-boundary defect and self-reported fix.')
add('reddit','AIDA','r/LocalLLaMA project discussion','Developer describes an MCP-connected pentesting container and asks for testers; community feedback is early and anecdotal.','secondary Reddit reviewed','https://www.reddit.com/r/LocalLLaMA/comments/1rvj08j/an_open_source_tool_that_gives_your_ai_a_full/',recovered+' Self-reported project description; not independent validation.')
add('official-issue','Dark Moon','Issue #40 privacy/tokenization report','Issue reports URL/domain/path and prompt tokenization privacy gaps; maintainer later reported a fix and added privacy tests.','primary issue reviewed; release/code verification deferred','https://github.com/ASCIT31/Dark-Moon/issues/40',recovered+' Treat fix/test claims as unverified until exact release and image are checked.')
add('official-release','Dark Moon','Releases','Release history includes v1.5.0 (2026-09-25); subsequent Oct 2026 commits advertise added privacy controls/tests.','primary releases page reviewed','https://github.com/ASCIT31/Dark-Moon/releases',recovered+' Autonomous exploitation still conflicts with direct ASM execution.')
add('official-code','CAI','Archived repository','CAI cybersecurity-agent framework; repository archived 2026-08-28, final snapshot v1.1.5.','primary repo reviewed','https://github.com/aliasrobotics/cai',recovered+' Architecture/reference only; not a maintained candidate.')
add('official-license','CAI','Archive LICENSE','Mixed license: permissive components plus research-only restrictions on designated additions; commercial/professional use requires separate grant.','primary license reviewed','https://github.com/aliasrobotics/cai/blob/archive/LICENSE',recovered+' Read component notices; do not assume whole repository is MIT.')
add('research-paper','CAI','Cybersecurity AI (CAI) Dataset','Author paper (2026-05-27) claims 230,935 session logs/26,027,742 prompts from 16,768 source IPs, across 23,147 target domains; it states operators routinely pasted real credentials/hostnames/tokens and access is limited to partners/customers.','secondary research paper/PDF reviewed','https://arxiv.org/abs/2605.28146',recovered+' Claims are author-reported, not an independent audit; useful privacy warning, not a verified runtime/configuration fact.')
add('youtube','BloodHound CE','First Look video','Historical UI/graph workflow and architecture orientation.','secondary transcript reviewed earlier; link re-indexed','https://www.youtube.com/watch?v=1EQoJHQl7ik',recovered+' Older product tour; not current feature/license proof.')
add('youtube','GPOZaurr','French 2024 presentation/demo','Shows report workflow and PowerShell use for GPO analysis.','secondary transcript reviewed earlier; link re-indexed','https://www.youtube.com/watch?v=WCXrwHIsdsY',recovered+' Vendor/demo content; not proof of licensing or safe remediation.')
add('conference-talk','Locksmith','Wild West Hackin’ Fest Toolshed talk','Talk page describes AD CS checks and remediation scope.','secondary talk transcript reviewed','https://www.hub.trimarcsecurity.com/post/wild-west-hackin-fest-toolshed-talk-locksmith',recovered+' Remediation features and Commons Clause are separately checked.')
add('reddit','Active Directory hardening','r/activedirectory hardening discussion','Community recommends combining posture tools, attack-path analysis and staged remediation; points to gaps such as SYSVOL content.','secondary Reddit reviewed','https://www.reddit.com/r/activedirectory/comments/1h4x9bq/ad_hardening/',recovered+' Anecdotal advice only.')

# Three internal ASM baseline sources; these are not public/external references.
add('internal-plan','ASM','ПЛАН.md','Operator-approved goals, operating sequence and ASM constraints used as comparison baseline.','local file reviewed; unchanged','file:///home/user/asm/%D0%9F%D0%9B%D0%90%D0%9D.md','Internal baseline; do not publish customer-specific context.')
add('internal-code','ASM','asm/agent.py','Action registry, risk categories and approval/gate behavior; inside_ad_collect creates a manual operator handoff rather than launching SharpHound over the network.','local code reviewed; unchanged','file:///home/user/asm/asm/agent.py','Static reading only; no code modifications.')
add('internal-code','ASM','asm/engines.py','Enumerates the current 19 scanner/analysis engines used for web, network, secrets and code analysis.','local code reviewed; unchanged','file:///home/user/asm/asm/engines.py','Static reading only; no code modifications.')

# Newly gathered sources S091-S135.
add('official-docs','NetExec','Database General Usage','NetExec automatically stores used/dumped credentials and other data in per-protocol SQLite workspaces under ~/.nxc/workspaces.','primary docs reviewed','https://www.netexec.wiki/getting-started/database-general-usage','Credentials and findings persist locally; isolate/handle as secrets.')
add('official-docs','NetExec','Bloodhound Ingestor','Documents built-in LDAP BloodHound collection and selectable collection methods.','primary docs reviewed','https://www.netexec.wiki/ldap-protocol/bloodhound-ingestor','--collection All should be treated as broad network collection, not a passive local operation.')
add('official-docs','NetExec','Spidering Shares','Documents SMB spidering and spider_plus; DOWNLOAD_FLAG=True copies all readable files to the operator host.','primary docs reviewed','https://www.netexec.wiki/smb-protocol/spidering-shares','File retrieval is outside current safe scope; explicit module and output gate required.')
add('official-docs','NetExec','Using Modules','Shows broad module surface and arbitrary per-module options; modules include command execution and credential extraction.','primary docs reviewed','https://www.netexec.wiki/getting-started/using-modules','Do not expose generic module execution to the agent.')
add('official-code','RustHound-CE','Repository','MIT-licensed Rust BloodHound CE collector; issue/release describe a WebClient service probe alongside AD collection.','primary repo/license/release reviewed; code audit deferred','https://github.com/g0h4n/RustHound-CE','Possible SharpHound overlap; whether this changes coverage versus the exact ASM handoff version is unverified. Do not count as a new capability until statically compared.')
add('official-release','RustHound-CE','v2.5.22 release','Released 2026-10-04; adds a WebClient/WebDAV probe via authenticated SMB IPC$ and includes it under All.','primary release reviewed','https://github.com/g0h4n/RustHound-CE/releases/tag/v2.5.22','This adds one SMB session per active computer; treat as an active network probe.')
add('official-issue','RustHound-CE','Issue #72 WebClient probe','Documents SMB2 IPC$ TREE_CONNECT plus a named-pipe CREATE; any domain user can query the service state, no local admin required.','primary issue reviewed','https://github.com/g0h4n/RustHound-CE/issues/72','Read-only by design but creates authenticated connections/logs and reveals coercion prerequisites.')
add('official-docs','RustHound-CE','HELP.md command surface','Default collection method is All (LDAP, SMB, HTTP); DCOnly avoids computer connections and uses LDAP only.','primary help source reviewed','https://github.com/g0h4n/RustHound-CE/blob/main/HELP.md','Documentation states command defaults; actual versioned code must be checked before use.')
add('official-package','RustHound-CE','crates.io package','Rust package version and publication lag relative to GitHub releases.','primary package page reviewed','https://crates.io/crates/rusthound-ce','Pin an exact artifact/commit; registry version can lag upstream tags.')
add('official-code','BloodHound.py CE','Community Edition branch','CE-compatible Python ingestor source branch; README page shows the branch last updated 2025-01-02.','primary branch and README reviewed; source audit deferred','https://github.com/dirkjanm/BloodHound.py/tree/bloodhound-ce','Source branch is stale relative to PyPI bloodhound-ce 1.9.1 (published 2025-10-24); verify the package-to-source correspondence and supply-chain provenance.')
add('official-code','BloodHound.py CE','README on CE branch','Documents CE ingestor methods including default, DCOnly and All; Experimental includes service/scheduled-task credential searches.','primary README reviewed','https://github.com/dirkjanm/BloodHound.py/blob/bloodhound-ce/README.md','README page shows last update 2025-01-02; Experimental and LoggedOn require separate review; compare the exact package artifact before considering.')
add('official-package','BloodHound.py CE','PyPI bloodhound-ce','Package metadata identifies version 1.9.1 and MIT; publication provenance should be checked.','primary package reviewed','https://pypi.org/project/bloodhound-ce/','PyPI page notes package publication not via Trusted Publishing; verify artifact hashes/source before use.')
add('official-code','ADACLScanner','Repository','Active PowerShell AD ACL analysis tool; current version 9.6 (2026-07-07), with fine-grained ACE/delegation queries including LAPS-access ACLs.','primary repository and release verified; code audit deferred','https://github.com/canix1/ADACLScanner','Complementary ACL visibility; select read-only properties carefully so secrets are not collected unnecessarily.')
add('official-license','ADACLScanner','license.md','Microsoft Public License (Ms-PL); commercial use permitted subject to notice/conditions.','primary license reviewed','https://github.com/canix1/ADACLScanner/blob/master/license.md','License page verified as Microsoft Public License; retain notices if redistributing.')
add('official-release','ADACLScanner','Releases','Latest release is 9.6 (2026-07-07); release page provides a SHA-256 and verified tag.','primary release page reviewed','https://github.com/canix1/ADACLScanner/releases','Pin the 9.6 source/tag and published SHA-256 before static review.')
add('official-code','NetExec','Repository','Current source tree for multi-protocol network assessment tool.','primary repo reviewed; code audit deferred','https://github.com/Pennyw0rth/NetExec','Many operations include execution, file transfer, secret extraction and mutation.')
add('official-release','NetExec','Releases','Version history and release recency.','primary releases reviewed','https://github.com/Pennyw0rth/NetExec/releases','Pin an exact tag; do not use floating package installs.')
add('official-license','NetExec','LICENSE','BSD-2-Clause.','primary license reviewed','https://github.com/Pennyw0rth/NetExec/blob/main/LICENSE','License allows commercial use subject to notices; behavior remains subject to strict gates.')
add('official-release','NetExec','v1.5.1 release','Release dated 2026-02-23 includes a fix for arbitrary file write in spider_plus.','primary release reviewed','https://github.com/Pennyw0rth/NetExec/releases/tag/v1.5.1','Use fixed version only; statically inspect exact module and dependency before selecting.')
add('official-code-locator','NetExec','spider_plus module source','Candidate source file for static review of SMB traversal, output paths and file-write logic.','source locator recorded; not downloaded','https://github.com/Pennyw0rth/NetExec/blob/v1.5.1/nxc/modules/spider_plus.py','No execution; inspect pinned v1.5.1 source before any inclusion.')
add('official-docs','NetExec','Audit Mode','Audit Mode redacts credentials from console output only; it is not a command gate or output/database sanitizer.','primary docs reviewed','https://www.netexec.wiki/getting-started/configuration/audit-mode','No generic direct CLI access; keep credentials out of raw arguments and isolate the database.')
add('official-code','AzureHound','Repository','Local Entra ID/Azure ARM graph collector; maps roles/PIM and related relationships.','primary repo reviewed; code audit deferred','https://github.com/SpecterOps/AzureHound','GPL-3.0; output is a sensitive identity graph.')
add('official-license','AzureHound','LICENSE.md','GNU GPL v3.0.','primary license reviewed','https://github.com/SpecterOps/AzureHound/blob/main/LICENSE.md','Review copyleft obligations if modified/redistributed.')
add('official-release','AzureHound','v3.1.1 release','Current release noted as 2026-09-08.','primary release reviewed','https://github.com/SpecterOps/AzureHound/releases/tag/v3.1.1','Pin binary/source version and verify checksum before later static inspection.')
add('official-docs','AzureHound','Data permissions','Lists granular Graph application permissions and custom Azure RBAC role; admin consent/preconfiguration are required.','primary permissions docs reviewed','https://bloodhound.specterops.io/collect-data/azurehound-data-permissions','Collection uses Graph/ARM GETs; no permission setup should be automated by ASM.')
add('official-docs','BloodHound OpenGraph','Overview','OpenGraph is a custom graph-data import/extension mechanism, not a collector.','primary docs reviewed','https://bloodhound.specterops.io/opengraph/overview','Structured graph features require compatible BloodHound CE and data schema mapping.')
add('official-docs','BloodHound OpenGraph','Graph data schema','Documents graph node/edge/payload structure and schema constraints for custom data.','primary schema reviewed','https://bloodhound.specterops.io/opengraph/developer/graph-data','Generic graph analysis is more limited; CE 8+ and PostgreSQL required for full structured support per docs.')
add('official-code','Maester','Latest tagged source candidate','Latest release page lists signed 2.2.97-preview (2026-10-05, commit 02b67aa); 2.2 adds 269 opt-in on-prem AD checks.','primary repo/release/blog reviewed; source audit deferred','https://github.com/maester365/maester/releases/tag/2.2.97-preview','Pre-release, not stable; pin full commit 02b67aa05904e68fffcc5bd2dd38bd1bb25ba6a1. MIT; test selection and Graph/LDAP scopes must be explicitly constrained.')
add('official-license','Maester','LICENSE','MIT license.','primary license reviewed','https://github.com/maester365/maester/blob/main/LICENSE','Dependencies and any added tests/scripts should be reviewed separately.')
add('official-docs','Maester','Test overview','Describes test catalogue and opt-in behavior, including AD/Entra/M365 assessments.','primary docs reviewed','https://maester.dev/docs/tests/','Only approved test IDs should be made callable through ASM.')
add('official-docs','Maester','Connect-Maester','Documents Graph connection scopes; -Privileged adds the write-named RoleEligibilitySchedule.ReadWrite.Directory permission.','primary command docs reviewed','https://maester.dev/docs/commands/Connect-Maester/','Default permissions may be read-oriented; do not enable -Privileged until its write-named scope and exact tests are approved.')
add('official-docs','Maester','GitHub Actions monitoring setup','Workflow setup grants many Graph application permissions; shortcut creates an Entra app, consents scopes, adds federation and writes GitHub Actions secrets.','primary docs reviewed','https://maester.dev/docs/monitoring/github/','Optional ReportSettings.ReadWrite.All disables report obfuscation; setup is state-changing and not a read-only onboarding. Do not run its helper automatically.')
add('official-blog','Maester','2.2 release overview','Vendor/project release article reports 269 opt-in AD checks and 2.2 features.','primary release article reviewed','https://maester.dev/blog/maester-2-2/','Use test-level source/code verification rather than counts in marketing material.')
add('official-code','Prowler','Repository','Local CLI CSPM for cloud providers; latest source release listed is 5.44.0 (2026-09-29). Prowler Cloud/SaaS is separate and out of scope.','primary repo and release list reviewed; code audit deferred','https://github.com/prowler-cloud/prowler','Apache-2.0; cloud-specific checks may have side effects or sensitive outputs. Assess local CLI only.')
add('official-docs','Prowler','AWS authentication','Documents AWS credential/profile/role authentication for local CLI.','primary docs reviewed','https://docs.prowler.com/user-guide/providers/aws/authentication','Use read-only least privilege and do not expose credentials in command arguments/logs.')
add('official-docs','Prowler','Azure authentication','Prowler Azure setup can require Graph scopes plus a custom ProwlerRole containing Microsoft.Web/sites/host/listkeys/action and Microsoft.Web/sites/config/list/Action.','primary docs and custom-role JSON reviewed','https://docs.prowler.com/user-guide/providers/azure/authentication','These actions can return app keys/config and cross the secret-handling boundary; skip checks needing ProwlerRole unless separately authorized. Admin consent/role assignment are operator actions, never ASM setup.')
add('official-docs','Prowler','GCP authentication','Documents local CLI authentication methods for Google Cloud.','primary authentication docs reviewed','https://docs.prowler.com/user-guide/providers/gcp/authentication','Requires Viewer, Service Usage Consumer, and a custom role for some checks; API enablement and role changes are operator actions, not ASM setup steps.')
add('official-license','Prowler','LICENSE','Apache License 2.0.','primary license reviewed','https://github.com/prowler-cloud/prowler/blob/master/LICENSE','Check subcomponents/dependencies for their own license notices.')
add('official-code','Entra App Exposure','Repository','Read-only PowerShell assessment focused on application registrations/service principals, OAuth permissions, ownership, credential metadata and evidence-linked findings; PowerShell 7.6+ and Commercial cloud only.','primary repo/README reviewed; source audit deferred','https://github.com/0xDarknightHacks/EntraAppExposure','v1.0.0 is a new/small project; Directory.Read.All requires admin consent and optional AuditLog.Read.All; local snapshots are sensitive; consultant/client labels must be checked for anonymity.')
add('official-license','Entra App Exposure','LICENSE','Apache License 2.0.','primary license reviewed','https://github.com/0xDarknightHacks/EntraAppExposure/blob/main/LICENSE','Commercial use allowed subject to notice/attribution conditions.')
add('official-release','Entra App Exposure','v1.0.0 release','Initial stable release on 2026-09-17; documents read-only Graph collection and zero Graph calls after snapshot.','primary release reviewed','https://github.com/0xDarknightHacks/EntraAppExposure/releases','Claims require static source review; small single-maintainer project.')
add('official-security-docs','Entra App Exposure','SECURITY.md','Declares Graph transport boundaries, app-only SecretManagement, read-only requests, fail-closed snapshot checks and sensitive-data handling.','primary security policy reviewed','https://github.com/0xDarknightHacks/EntraAppExposure/blob/main/SECURITY.md','Self-authored invariants; verify the implementation and test coverage in static review.')
add('official-license','SharpHound CE','LICENSE on 2.X branch','SharpHound collector source is GPL-3.0; current v2.17.0 release is separate from BloodHound CE server licensing.','primary license reviewed','https://github.com/SpecterOps/SharpHound/blob/2.X/LICENSE','Do not infer the server Apache-2.0 license applies to the collector; preserve GPL notices and check distribution obligations.')
add('youtube','Strix','Autonomous pentest demo','Demonstrates install/run workflow and autonomous tool use.','secondary video locator recorded; transcript reviewed earlier','https://www.youtube.com/watch?v=L8dmQGLCafk','Demonstration only; evidence of operational capability, not safety.')
add('official-release','ZAP Client Side Integration','v0.32.0 release','Latest Client Side Integration add-on release dated 2026-10-02; adds modern-app conditional crawling and fixes exclusion handling.','primary release page reviewed; signed tag verified','https://github.com/zaproxy/zap-extensions/releases/tag/client-v0.32.0','Tag commit 3ceb437398999debd50ed4446a9a7adca3914f62. Crawl interactions can still click/fill/navigate; scope exclusions do not make mutating actions safe.')

if len(extra) != 100:
    raise SystemExit(f'Expected 100 added rows (S036-S135), got {len(extra)}')
rows = prefix + [dict(item, id=f'S{i:03d}') for i, item in enumerate(extra, start=36)]
if len(rows) != 135 or [r['id'] for r in rows] != [f'S{i:03d}' for i in range(1,136)]:
    raise SystemExit('Row count/ID continuity check failed')

# URL-normalized duplicate check. Query parameters are retained except tracking keys.
def norm_url(value):
    if value.startswith('file://'):
        return value.lower()
    p = urlsplit(value.strip())
    host = p.netloc.lower()
    path = re.sub(r'/+', '/', p.path or '/')
    if path != '/':
        path = path.rstrip('/')
    query = [(k, v) for k, v in parse_qsl(p.query, keep_blank_values=True)
             if not k.lower().startswith('utm_') and k.lower() not in {'fbclid','gclid'}]
    query.sort()
    return urlunsplit((p.scheme.lower(), host, path, urlencode(query, doseq=True), ''))
seen = {}
for row in rows:
    if not all(row.get(k) for k in FIELDS if k != 'notes'):
        raise SystemExit(f'Empty required field in {row.get("id")}')
    key = norm_url(row['canonical_url'])
    if key in seen:
        raise SystemExit(f'URL duplicate: {seen[key]} and {row["id"]}: {key}')
    seen[key] = row['id']

with TEMP.open('w', encoding='utf-8', newline='') as f:
    writer = csv.DictWriter(f, fieldnames=FIELDS, lineterminator='\n')
    writer.writeheader()
    writer.writerows(rows)

counts = {}
for row in rows:
    counts[row['source_type']] = counts.get(row['source_type'], 0) + 1
print(f'WROTE_TEMP={TEMP}')
print(f'ROWS={len(rows)} EXTERNAL={sum(not r["source_type"].startswith("internal-") for r in rows)} INTERNAL={sum(r["source_type"].startswith("internal-") for r in rows)} UNIQUE_NORMALIZED_URLS={len(seen)}')
print('TYPE_COUNTS=' + ', '.join(f'{k}:{v}' for k,v in sorted(counts.items())))
print('PREFIX_AND_BACKUP_MATCH=YES')
